### ISSUE TITLE
[Suggestion] Per-directory config

### ISSUE THREAD

**Issue by OpenRift412** [solemnwarning/ipxwrapper#15]
For games that require different configurations to work properly, it might be best to have some sort of way to have IPXWrapper use a same-directory config instead of all installations of it using the same one.

**Comment by solemnwarning** [comment]
Any settings in particular which some games need and others don't like?

**Comment by FunkyFr3sh** [comment]
> Any settings in particular which some games need and others don't like?

@solemnwarning  We need at least a per-directory config for the DOSBox servers because they differ on each game (Each community hosting their own servers)

It would also be cool if the DOSBox server could be turned into a drop down so you can add multiple servers.
e.g.
europe.ipxbox.domain.com
asia.ipxbox.domain.com
us-east.ipxbox.domain.com
us-west.ipxbox.domain.com

**Comment by solemnwarning** [comment]
I've added support for reading (some) of the configuration from an `ipxwrapper.ini` file in the same directory as the game exe, this is a build including it:

[ipxwrapper-git.zip](https://github.com/user-attachments/files/15976181/ipxwrapper-git.zip)

And an example ini: [ipxwrapper.ini.example](https://github.com/solemnwarning/ipxwrapper/blob/master/ipxwrapper.ini.example)

**Comment by FunkyFr3sh** [comment]
ipxconfig.exe is not supposed to read the .ini I guess? It doesn't seem to display the settings found in `ipxwrapper.ini`

Could not play a test game yet, but I guess it will automatically switch the `Encapsulation Type` to DOSBox Udp when dosbox server/port are uncommented?

**Comment by solemnwarning** [comment]
Yes, ipxconfig just saves/loads settings from the registry, only the DLLs will look for ipxwrapper.ini
