### ISSUE TITLE
Is there a way to configure IPXWrapper without going online and using Lutris or Bottles?

### ISSUE THREAD

**Issue by eband** [solemnwarning/ipxwrapper#16]
In order to use your IPX wrappers on Wine without Lutris, Bottles, or any kind of frontend that doesn't involve going online or automate installation, what do I do?

I am not a fan of going online to install some features, and if you want to think I like to fuss, then please do so. I like to keep everything offline unless if it's multiplayer or if I really have to go.

So I ask again, is there a way to configure IPXWrapper without using Lutris or Bottles?

If not, just tell me to piss off and I'll take my business elsewhere.

**Comment by solemnwarning** [comment]
You don't need any kind of launcher or frontend, just drop the files alongside the game like [the readme](https://github.com/solemnwarning/ipxwrapper/blob/master/readme.txt) says.

**Comment by robertyutintat** [comment]
OK, I am reopening this issue because I have tried the prescribed steps and yet, Warcraft II does not work on IPX LAN when using Wine.

I have tried the following:
- copy all the DLLs to the game directory
- run the 64-bit registry key
- override the wsock.dll library as native, built-in
- installed directplay through winetricks
- did everything listed above using the newest version, which is, of the time of writing, is version 0.70

I am using Linux Mint 22 Wilma and the Wine version is version 9.0 Stable. Funny thing is, ipxwrapper.log is nowhere to be seen. I know, I know, it should be in the same directory as the extracted DLLs, but even after I did a search on the home folder, it's still nowhere to be found, so sorry, I can't determine the error.
